"use client";

import { FormEvent, useState } from "react";
import { useAuth } from "@/components/AuthProvider";
import { ApiError, apiFetch } from "@/lib/api";
import { postTurn, speakerLabel, type SimMessage, type SimulationSession } from "@/lib/simulation/api";

export default function InterviewPage() {
  const { token, getAccessToken } = useAuth();
  const [title, setTitle] = useState(""); const [scenario, setScenario] = useState("");
  const [session, setSession] = useState<SimulationSession | null>(null); const [messages, setMessages] = useState<SimMessage[]>([]);
  const [draft, setDraft] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function accessToken() { return token ?? await getAccessToken(); }
  async function start(event: FormEvent) { event.preventDefault(); const access = await accessToken(); if (!access) return; setBusy(true); setError(null); try { const created = await apiFetch<SimulationSession>("/api/patients/manual", { method: "POST", token: access, body: { title, scenario } }); setSession(created); setMessages([]); setDraft(""); } catch (err) { setError(err instanceof ApiError ? err.message : "Nie udało się utworzyć przypadku."); } finally { setBusy(false); } }
  async function send(event: FormEvent) { event.preventDefault(); if (!session || !draft.trim()) return; const access = await accessToken(); if (!access) return; setBusy(true); setError(null); try { const updated = await postTurn(access, session.conversation_id, draft.trim(), "doctor_asks"); setSession(updated); setMessages(updated.messages ?? []); setDraft(""); } catch (err) { setError(err instanceof ApiError ? err.message : "Nie udało się wysłać wiadomości."); } finally { setBusy(false); } }
  return <main className="app-page flex min-h-0 flex-1 flex-col"><h1 className="text-3xl">Wywiad</h1>{!session ? <form className="classical-card mt-5 max-w-2xl space-y-4 p-4" onSubmit={(event) => void start(event)}><p className="text-sm text-[var(--color-soft)]">Utwórz prywatny przypadek ćwiczeniowy. Nie wpisuj danych umożliwiających identyfikację pacjenta.</p><label className="block text-sm" htmlFor="case-title">Tytuł przypadku<input id="case-title" className="mt-1 min-h-11 w-full rounded border border-[var(--color-divider)] bg-[var(--color-bg)] px-3" value={title} maxLength={120} onChange={(event) => setTitle(event.target.value)} placeholder="np. Ból w klatce piersiowej" /></label><label className="block text-sm" htmlFor="case-scenario">Opis pacjenta i sytuacji<textarea id="case-scenario" className="mt-1 min-h-48 w-full rounded border border-[var(--color-divider)] bg-[var(--color-bg)] p-3" value={scenario} minLength={20} maxLength={12000} required onChange={(event) => setScenario(event.target.value)} placeholder="Opisz objawy, wiek oraz istotny kontekst medyczny…" /></label><button className="classical-btn classical-btn-primary" disabled={busy || scenario.trim().length < 20} type="submit">Rozpocznij wywiad</button></form> : <><div className="mt-4 flex items-center justify-between"><p className="text-sm text-[var(--color-soft)]">{session.title}</p><button className="classical-btn text-sm" type="button" onClick={() => { setSession(null); setMessages([]); setScenario(""); setTitle(""); }}>Nowy przypadek</button></div><section className="mt-5 min-h-0 flex-1 overflow-y-auto"><ol className="space-y-3">{messages.map((message) => <li className="classical-card p-3" key={message.id}><p className="text-xs font-semibold text-[var(--color-soft)]">{speakerLabel("doctor_asks", message.role)}</p><p className="mt-1 whitespace-pre-wrap">{message.content}</p></li>)}</ol></section><form className="mt-4 flex gap-2" onSubmit={(event) => void send(event)}><input className="min-h-11 min-w-0 flex-1 rounded border border-[var(--color-divider)] bg-[var(--color-bg)] px-3" value={draft} disabled={busy} onChange={(event) => setDraft(event.target.value)} placeholder="Zadaj pytanie pacjentowi…" /><button className="classical-btn classical-btn-primary" type="submit" disabled={busy || !draft.trim()}>Wyślij</button></form></>}{error ? <p className="mt-4 text-sm text-amber-200" role="alert">{error}</p> : null}</main>;
}
